---
- hosts: all
  gather_facts: yes

  tasks:
    - name: Check Files Existence
      shell: "ls -al /home/{{ lookup('env','USER') }}/ansible.touch"
      register: output

    - name: Print Output
      debug:
        msg: "{{ output.stdout }}"

    - name: Get hostname
      command: /bin/hostname
      register: my_hostname

    - debug: var=my_hostname

    - name: Host Uptime
      shell: /usr/bin/uptime
      register: result
      when: ansible_os_family == "Debian"

    - debug:
        msg: "{{ result.stdout_lines }}"
